const ALL_PRODUCTS = 'ALL_PRODUCTS';
const SELECTED_PRODUCTS = 'SELECTED_PRODUCTS';
const DELIVERY_ADDRESS = 'DELIVERY_ADDRESS';
const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
const DECREASE_QUANTITY = 'DECREASE_QUANTITY';

export default {
    ALL_PRODUCTS, 
    SELECTED_PRODUCTS, 
    DELIVERY_ADDRESS,
    INCREASE_QUANTITY,
    DECREASE_QUANTITY
}